### ISSUE TITLE
which tensorflow version do you used

### ISSUE THREAD

**Issue by lizhenping** [DongKeee/DDIExtraction#3]
i usde tensorflow1.5, some times it will break donw .

**Comment by wangdsh** [comment]
@zhenpingli  有没有文章对应的处理后的数据集，交流一下～

**Comment by lizhenping** [comment]
> @zhenpingli 有没有文章对应的处理后的数据集，交流一下～

我上传到了百度云盘，请查收或者你发你的邮箱

**Comment by zhenpingli** [comment]
> @zhenpingli 有没有文章对应的处理后的数据集，交流一下～

链接：https://pan.baidu.com/s/1o9iPWI3wexVa0VnbKEpiHQ 
提取码：7oy0 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by lizhenping** [comment]
> @zhenpingli 有没有文章对应的处理后的数据集，交流一下～

链接：https://pan.baidu.com/s/1o9iPWI3wexVa0VnbKEpiHQ 
提取码：7oy0 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by wangdsh** [comment]
> > @zhenpingli 有没有文章对应的处理后的数据集，交流一下～
> 
> 链接：https://pan.baidu.com/s/1o9iPWI3wexVa0VnbKEpiHQ
> 提取码：7oy0
> 复制这段内容后打开百度网盘手机App，操作更方便哦

链接失效了，麻烦发我邮箱吧，neuwdsh@163.com，谢谢

**Comment by yangxia605** [comment]
能不能麻烦您也给我发一份数据，谢谢。我的邮箱：2019223049293@stu.scu.edu.cn

**Comment by yangxia605** [comment]
@zhenpingli 你好，请问你有遇到这个问题吗？
Traceback (most recent call last):
File "main.py", line 283, in
validation_data=([left_x_test, test_array, right_x_test, test_postion1, test_postion2], test_label_cat),verbose=1)
File "/Users/mianmian/opt/anaconda3/lib/python3.7/site-packages/keras/engine/training.py", line 1039, in fit
validation_steps=validation_steps)
File "/Users/mianmian/opt/anaconda3/lib/python3.7/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
outs = f(ins_batch)
File "/Users/mianmian/opt/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in call
return self._call(inputs)
File "/Users/mianmian/opt/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "/Users/mianmian/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in call
run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[10,0] = 13653 is not in [0, 13653)
[[{{node embedding_1_1/embedding_lookup}}]]

**Comment by zhuzhumiao** [comment]
可以给我发一份处理后的数据集吗？我的邮箱是 2917477091@qq.com
